\c trailmetrics;

CREATE TABLE activities (
    id BIGINT PRIMARY KEY,
    athlete_id BIGINT,
    average_cadence DOUBLE PRECISION,
    average_speed DOUBLE PRECISION,
    average_temp INTEGER,
    average_watts DOUBLE PRECISION,
    description TEXT,
    distance DOUBLE PRECISION,
    has_heartrate BOOLEAN,
    map_polyline TEXT,
    max_speed DOUBLE PRECISION,
    moving_time INTEGER,
    "name" VARCHAR(255),
    sport_type VARCHAR(255),
    start_date TIMESTAMPTZ(6),
    total_elevation_gain DOUBLE PRECISION,
    "type" VARCHAR(255),
    weighted_average_watts DOUBLE PRECISION
);
CREATE INDEX idx_activities_athlete_id ON activities(athlete_id);

CREATE TABLE activity_streams (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "data" JSON,
    original_size INTEGER,
    resolution VARCHAR(255),
    series_type VARCHAR(255),
    "type" VARCHAR(255),
    activity_id BIGINT NOT NULL,
    CONSTRAINT activity_streams_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE
);

CREATE TABLE user_preferences (
    user_id BIGINT PRIMARY KEY,
    sync_years INTEGER,
    time_zone VARCHAR(255)
);

CREATE TABLE segments (
    segment_id VARCHAR(50) PRIMARY KEY,
    activity_id BIGINT NOT NULL,
    user_id VARCHAR(255),
    start_distance INTEGER,
    end_distance INTEGER,
    segment_length INTEGER,
    avg_gradient DOUBLE PRECISION,
    avg_cadence DOUBLE PRECISION,
    movement_type VARCHAR(20),
    "type" VARCHAR(20),
    grade_category DOUBLE PRECISION,
    start_lat DOUBLE PRECISION,
    end_lat DOUBLE PRECISION,
    start_lng DOUBLE PRECISION,
    end_lng DOUBLE PRECISION,
    start_altitude INTEGER,
    end_altitude INTEGER,
    start_time INTEGER,
    end_time INTEGER,
    start_heartrate INTEGER,
    end_heartrate INTEGER,
    avg_heartrate INTEGER,
    avg_speed DOUBLE PRECISION,
    elevation_gain INTEGER,
    hr_drift DOUBLE PRECISION, 
    road_type VARCHAR(255),
    surface_type VARCHAR(255),
    temperature DOUBLE PRECISION,
    feels_like DOUBLE PRECISION,
    humidity INTEGER,
    wind DOUBLE PRECISION,
    weather_id INTEGER,
    weather_main VARCHAR(255),
    weather_description VARCHAR(255),
    efficiency_score DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activity_status_tracker (
    activity_id BIGINT PRIMARY KEY,
    segment_status BOOLEAN DEFAULT FALSE,
    terrain_status BOOLEAN DEFAULT FALSE,
    weather_status BOOLEAN DEFAULT FALSE,
    not_processable BOOLEAN DEFAULT FALSE,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE weather_data_progress (
    activity_id BIGINT NOT NULL,               
    group_id VARCHAR(20) NOT NULL,            
    total_groups INT NOT NULL,                 
    saved BOOLEAN DEFAULT FALSE,               
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (activity_id, group_id),      
    CONSTRAINT check_group_order CHECK (CAST(SPLIT_PART(group_id, '_', 1) AS INT) <= total_groups) 
);

CREATE TABLE segment_similarity (
    segment_id_1 VARCHAR(50) NOT NULL,
    segment_id_2 VARCHAR(50) NOT NULL,
    similarity_score REAL NOT NULL,
    calculated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Optional: Add information about the similarity calculation method or parameters
    -- calculation_method VARCHAR(255),
    -- calculation_params JSONB,
    FOREIGN KEY (segment_id_1) REFERENCES segments(segment_id),
    FOREIGN KEY (segment_id_2) REFERENCES segments(segment_id),
    PRIMARY KEY (segment_id_1, segment_id_2)
);

-- Index for faster lookups based on either segment ID
CREATE INDEX idx_segment_similarity_1 ON segment_similarity (segment_id_1);
CREATE INDEX idx_segment_similarity_2 ON segment_similarity (segment_id_2);

-- Optional index for querying by similarity score
CREATE INDEX idx_segment_similarity_score ON segment_similarity (similarity_score DESC);

CREATE TABLE similarity_status_fingerprint (
    user_id BIGINT PRIMARY KEY,
    similarity_calculated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    activity_fingerprint TEXT NOT NULL,
    in_progress BOOLEAN DEFAULT FALSE
);
