-- Connect to activity_service database
\c activity_service;

CREATE TABLE activities (
    id BIGINT PRIMARY KEY,
    athlete_id BIGINT,
    average_cadence DOUBLE PRECISION,
    average_speed DOUBLE PRECISION,
    average_temp INTEGER,
    average_watts DOUBLE PRECISION,
    description TEXT,
    distance DOUBLE PRECISION,
    has_heartrate BOOLEAN,
    map_polyline TEXT,
    max_speed DOUBLE PRECISION,
    moving_time INTEGER,
    "name" VARCHAR(255),
    sport_type VARCHAR(255),
    start_date TIMESTAMPTZ(6),
    total_elevation_gain DOUBLE PRECISION,
    "type" VARCHAR(255),
    weighted_average_watts DOUBLE PRECISION
);

CREATE TABLE activity_streams (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "data" JSON,
    original_size INTEGER,
    resolution VARCHAR(255),
    series_type VARCHAR(255),
    "type" VARCHAR(255),
    activity_id BIGINT NOT NULL,
    CONSTRAINT activity_streams_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE
);

CREATE TABLE user_preferences (
    user_id BIGINT PRIMARY KEY,
    sync_years INTEGER,
    time_zone VARCHAR(255)
);

-- Connect to analytics_service database
\c analytics_service;

CREATE TABLE segments (
    id SERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL,
    start_distance DOUBLE PRECISION NOT NULL,
    end_distance DOUBLE PRECISION NOT NULL,
    segment_length DOUBLE PRECISION NOT NULL,
    avg_gradient DOUBLE PRECISION NOT NULL,
    avg_cadence DOUBLE PRECISION NOT NULL,
    movement_type VARCHAR(20) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    grade_category DOUBLE PRECISION NOT NULL,
    start_lat DOUBLE PRECISION NOT NULL,
    end_lat DOUBLE PRECISION NOT NULL,
    start_lng DOUBLE PRECISION NOT NULL,
    end_lng DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
