\c trailmetrics;

INSERT INTO weather_icons (weather_id, description, icon) VALUES
(200, 'thunderstorm with light rain', 'wi-thunderstorm'),
(201, 'thunderstorm with rain', 'wi-thunderstorm'),
(202, 'thunderstorm with heavy rain', 'wi-thunderstorm'),
(210, 'light thunderstorm', 'wi-thunderstorm'),
(211, 'thunderstorm', 'wi-thunderstorm'),
(212, 'heavy thunderstorm', 'wi-thunderstorm'),
(221, 'ragged thunderstorm', 'wi-thunderstorm'),
(230, 'thunderstorm with light drizzle', 'wi-thunderstorm'),
(231, 'thunderstorm with drizzle', 'wi-thunderstorm'),
(232, 'thunderstorm with heavy drizzle', 'wi-thunderstorm'),
(300, 'light intensity drizzle', 'wi-showers'),
(301, 'drizzle', 'wi-showers'),
(302, 'heavy intensity drizzle', 'wi-showers'),
(310, 'light intensity drizzle rain', 'wi-showers'),
(311, 'drizzle rain', 'wi-showers'),
(312, 'heavy intensity drizzle rain', 'wi-showers'),
(313, 'shower rain and drizzle', 'wi-showers'),
(314, 'heavy shower rain and drizzle', 'wi-showers'),
(321, 'shower drizzle', 'wi-showers'),
(500, 'light rain', 'wi-day-rain'),
(501, 'moderate rain', 'wi-day-rain'),
(502, 'heavy intensity rain', 'wi-day-rain'),
(503, 'very heavy rain', 'wi-day-rain'),
(504, 'extreme rain', 'wi-day-rain'),
(511, 'freezing rain', 'wi-sleet'),
(520, 'light intensity shower rain', 'wi-showers'),
(521, 'shower rain', 'wi-showers'),
(522, 'heavy intensity shower rain', 'wi-showers'),
(531, 'ragged shower rain', 'wi-showers'),
(600, 'light snow', 'wi-snow'),
(601, 'snow', 'wi-snow'),
(602, 'heavy snow', 'wi-snow'),
(611, 'sleet', 'wi-sleet'),
(612, 'light shower sleet', 'wi-sleet'),
(613, 'shower sleet', 'wi-sleet'),
(615, 'light rain and snow', 'wi-rain-mix'),
(616, 'rain and snow', 'wi-rain-mix'),
(620, 'light shower snow', 'wi-snow'),
(621, 'shower snow', 'wi-snow'),
(622, 'heavy shower snow', 'wi-snow'),
(701, 'mist', 'wi-fog'),
(711, 'smoke', 'wi-smoke'),
(721, 'haze', 'wi-day-haze'),
(731, 'sand/dust whirls', 'wi-dust'),
(741, 'fog', 'wi-fog'),
(751, 'sand', 'wi-sandstorm'),
(761, 'dust', 'wi-dust'),
(762, 'volcanic ash', 'wi-volcano'),
(771, 'squalls', 'wi-strong-wind'),
(781, 'tornado', 'wi-tornado'),
(800, 'clear sky', 'wi-day-sunny'),
(801, 'few clouds', 'wi-day-cloudy'),
(802, 'scattered clouds', 'wi-cloud'),
(803, 'broken clouds', 'wi-cloudy'),
(804, 'overcast clouds', 'wi-cloudy');
