\c trailmetrics;
-- Create users
CREATE USER ${ACTIVITY_USER} WITH PASSWORD '${ACTIVITY_PASSWORD}';
CREATE USER ${ANALYTICS_USER} WITH PASSWORD '${ANALYTICS_PASSWORD}';
-- CREATE USER activity_user WITH PASSWORD 'LL9TgAjw3Ca4pCJ';
-- CREATE USER analytics_user WITH PASSWORD '103QKa3O4kpDnZA';

-- Privileges for activity_user
GRANT ALL PRIVILEGES ON SCHEMA public TO activity_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO activity_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO activity_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO activity_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO activity_user;

-- Privileges per analytics_user
GRANT ALL PRIVILEGES ON SCHEMA public TO analytics_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO analytics_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO analytics_user;