app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  jwt-cookie-name: ${JWT_COOKIE_NAME:TRAILMETRICS-JWT-TOKEN}
  encryption:
    secret-key: ${ENCRYPTION_SECRET_KEY}
    salt: ${ENCRYPTION_SALT}

auth-service:
  api-key: ${AUTH_SERVICE_API_KEY}

server:
  port: ${SERVER_PORT}
  error:
    whitelabel:
      enabled: false # Disables default Spring Boot error page
    include-message: always # Ensures errors return meaningful messages
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true

external-api:
  strava:
    refresh-token-url: 'https://www.strava.com/api/v3/oauth/token'

spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        provider:
          strava:
            authorization-uri: https://www.strava.com/oauth/authorize
            token-uri: https://www.strava.com/oauth/token
            user-info-uri: https://www.strava.com/api/v3/athlete
            user-name-attribute: id
        registration:
          strava:
            authorization-grant-type: authorization_code
            client-id: ${STRAVA_CLIENT_ID}
            client-name: Strava
            client-secret: ${STRAVA_CLIENT_SECRET}
            redirect-uri: '{baseUrl}/login/oauth2/code/strava'
            scope: read,activity:read_all

jwt:
  private-key-path: file:config/keys/private.pem
  public-key-path: file:config/keys/public.pem
  expiration-time: ${JWT_EXPIRATION:900000}

