app:
  frontend-url: http://localhost:5173
  jwt-cookie-name: TRAILMETRICS-JWT-TOKEN
  encryption:
    secret-key: YNLyUVdaoQ
    salt: ee729f61

auth-service:
  url: http://localhost:8080
  api-key: 019d3401-6011-4f50-bffe-6c1dd9ac735f
  public-key-url: http://localhost:8080/internal/public-key

server:
  port: 8081

spring:
  application:
    name: activity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/trailmetrics
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-group
      auto-offset-reset: earliest
      max-poll-records: 1  # Process one activity at a time (avoids API overload)
      enable-auto-commit: false  # Manually commit after processing
    listener:
      ack-mode: manual  # Only commit messages after successful processing
      missing-topics-fatal: false  # Prevent startup errors if topic is missing
    producer:
      retries: 5  # Retries for failed message publishing
      acks: all  # Ensures message delivery is confirmed



strava:
  api:
    base-url: https://www.strava.com/api/v3
    max-per-page: 200 # Pagination setting
    allowed-sport-types: "Run,Trail Run,Walk,Hike" # Only foot sports are considered
    instant-sync-limit: 10 # Max number of activities instantly synchronized
    rate-limit-short-window: 200  # Max 100 requests per 15 minutes
    read-rate-limit-short-window: 100  # Max 100 requests per 15 minutes
    rate-limit-daily: 2000  # Max 1000 requests per day
    read-rate-limit-daily: 1000  # Max 1000 requests per day
    rate-limit-sleep-minutes: 15  # Sleep for 15 minutes if short-term limit is reached


sync:
  default-sync-years: 6
  default-zone: "Europe/Rome"
