app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  jwt-cookie-name: ${JWT_COOKIE_NAME:TRAILMETRICS-JWT-TOKEN}
  encryption:
    secret-key: ${ENCRYPTION_SECRET_KEY}
    salt: ${ENCRYPTION_SALT}

auth-service:
  url: ${AUTH_SERVICE_URL}
  api-key: ${AUTH_SERVICE_API_KEY}
  public-key-url: ${AUTH_SERVICE_PUBLIC_KEY_URL}

server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: activity-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: activity-service-group
      auto-offset-reset: earliest
      max-poll-records: 1  # Process one activity at a time (avoids API overload)
      enable-auto-commit: false  # Manually commit after processing
    listener:
      ack-mode: manual  # Only commit messages after successful processing
      missing-topics-fatal: false  # Prevent startup errors if topic is missing
    producer:
      retries: 5  # Retries for failed message publishing
      acks: all  # Ensures message delivery is confirmed



strava:
  api:
    base-url: ${STRAVA_API_BASE_URL:https://www.strava.com/api/v3}
    max-per-page: ${STRAVA_API_MAX_PER_PAGE:200} # Pagination setting
    allowed-sport-types: "Run,Trail Run,Walk,Hike" # Only foot sports are considered
    rate-limit-short-window: ${STRAVA_API_RATE_LIMIT_SHORT_WINDOW:200}  # Max 100 requests per 15 minutes
    read-rate-limit-short-window: ${STRAVA_API_READ_RATE_LIMIT_SHORT_WINDOW:100}  # Max 100 requests per 15 minutes
    rate-limit-daily: ${STRAVA_API_RATE_LIMIT_DAILY:2000}  # Max 1000 requests per day
    read-rate-limit-daily: ${STRAVA_API_READ_RATE_LIMIT_DAILY:1000}  # Max 1000 requests per day
    rate-limit-sleep-minutes: ${STRAVA_API_RATE_LIMIT_SLEEP_MINUTES:15}  # Sleep for 15 minutes if short-term limit is reached


sync:
  default-sync-years: ${SYNC_DEFAULT_SYNC_YEARS:6}
  default-zone: ${SYNC_DEFAULT_ZONE}
